name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_CURL_VERBOSE: 1
      GIT_TRACE: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # or 'npx vite build' if you're using Vite directly

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # The folder your project builds into
